//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Net_EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_JobInfo
    {
        public int Id { get; set; }
        public string JobGroupName { get; set; }
        public string JobName { get; set; }
        public string TriggerName { get; set; }
        public string Cron { get; set; }
        public int TriggerState { get; set; }
        public System.DateTime JobStartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> PreTime { get; set; }
        public Nullable<System.DateTime> NextTime { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string TriggerGroupName { get; set; }
        public string DLLName { get; set; }
        public string FullJobName { get; set; }
        public bool Deleted { get; set; }
        public string Exception { get; set; }
        public string RequestUrl { get; set; }
    }
}
