//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Net_EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRTZ_SIMPLE_TRIGGERS
    {
        public string SCHED_NAME { get; set; }
        public string TRIGGER_NAME { get; set; }
        public string TRIGGER_GROUP { get; set; }
        public int REPEAT_COUNT { get; set; }
        public long REPEAT_INTERVAL { get; set; }
        public int TIMES_TRIGGERED { get; set; }
    
        public virtual QRTZ_TRIGGERS QRTZ_TRIGGERS { get; set; }
    }
}
