//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Net_EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QRTZ_FIRED_TRIGGERS
    {
        public string SCHED_NAME { get; set; }
        public string ENTRY_ID { get; set; }
        public string TRIGGER_NAME { get; set; }
        public string TRIGGER_GROUP { get; set; }
        public string INSTANCE_NAME { get; set; }
        public long FIRED_TIME { get; set; }
        public long SCHED_TIME { get; set; }
        public int PRIORITY { get; set; }
        public string STATE { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_GROUP { get; set; }
        public Nullable<bool> IS_NONCONCURRENT { get; set; }
        public Nullable<bool> REQUESTS_RECOVERY { get; set; }
    }
}
