//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Net_EFModel_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class qrtz_triggers
    {
        public string SCHED_NAME { get; set; }
        public string TRIGGER_NAME { get; set; }
        public string TRIGGER_GROUP { get; set; }
        public string JOB_NAME { get; set; }
        public string JOB_GROUP { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> NEXT_FIRE_TIME { get; set; }
        public Nullable<long> PREV_FIRE_TIME { get; set; }
        public Nullable<int> PRIORITY { get; set; }
        public string TRIGGER_STATE { get; set; }
        public string TRIGGER_TYPE { get; set; }
        public long START_TIME { get; set; }
        public Nullable<long> END_TIME { get; set; }
        public string CALENDAR_NAME { get; set; }
        public Nullable<short> MISFIRE_INSTR { get; set; }
        public byte[] JOB_DATA { get; set; }
    
        public virtual qrtz_blob_triggers qrtz_blob_triggers { get; set; }
        public virtual qrtz_cron_triggers qrtz_cron_triggers { get; set; }
        public virtual qrtz_job_details qrtz_job_details { get; set; }
        public virtual qrtz_simple_triggers qrtz_simple_triggers { get; set; }
        public virtual qrtz_simprop_triggers qrtz_simprop_triggers { get; set; }
    }
}
