//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Net_EFModel_MySql
{
    using System;
    using System.Collections.Generic;
    
    public partial class qrtz_simple_triggers
    {
        public string SCHED_NAME { get; set; }
        public string TRIGGER_NAME { get; set; }
        public string TRIGGER_GROUP { get; set; }
        public long REPEAT_COUNT { get; set; }
        public long REPEAT_INTERVAL { get; set; }
        public long TIMES_TRIGGERED { get; set; }
    
        public virtual qrtz_triggers qrtz_triggers { get; set; }
    }
}
