//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Net_EFModel_MySql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bihu_analyticsEntities : DbContext
    {
        public bihu_analyticsEntities()
            : base("name=bihu_analyticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<customer_quartzjobinfo> customer_quartzjobinfo { get; set; }
        public DbSet<qrtz_blob_triggers> qrtz_blob_triggers { get; set; }
        public DbSet<qrtz_calendars> qrtz_calendars { get; set; }
        public DbSet<qrtz_cron_triggers> qrtz_cron_triggers { get; set; }
        public DbSet<qrtz_fired_triggers> qrtz_fired_triggers { get; set; }
        public DbSet<qrtz_job_details> qrtz_job_details { get; set; }
        public DbSet<qrtz_locks> qrtz_locks { get; set; }
        public DbSet<qrtz_paused_trigger_grps> qrtz_paused_trigger_grps { get; set; }
        public DbSet<qrtz_scheduler_state> qrtz_scheduler_state { get; set; }
        public DbSet<qrtz_simple_triggers> qrtz_simple_triggers { get; set; }
        public DbSet<qrtz_simprop_triggers> qrtz_simprop_triggers { get; set; }
        public DbSet<qrtz_triggers> qrtz_triggers { get; set; }
    }
}
